"use client";
import { useReport } from "@/hooks/useReport";
import { LoadingSpinner } from "@/components/shared/LoadingSpinner";
import { getInvestmentPlans } from "@/lib/report-helpers";
import { formatCurrency } from "@/lib/utils";
import { useState } from "react";

const PROFILE_META: Record<string, { color: string; bg: string; border: string; icon: string; desc: string }> = {
  conservative: { color: "#10B981", bg: "rgba(16,185,129,0.06)", border: "rgba(16,185,129,0.2)", icon: "🛡️", desc: "Capital preservation with stable returns" },
  moderate:     { color: "#3B82F6", bg: "rgba(59,130,246,0.06)", border: "rgba(59,130,246,0.2)", icon: "⚖️", desc: "Balanced growth and safety"              },
  aggressive:   { color: "#F43F5E", bg: "rgba(244,63,94,0.06)",  border: "rgba(244,63,94,0.2)",  icon: "🚀", desc: "Maximum growth, higher risk tolerance"  },
};
const RISK_COLOR: Record<string, string> = {
  low: "#10B981", medium: "#F59E0B", high: "#F97316", very_high: "#F43F5E",
};
const SENTIMENT_STYLE: Record<string, { color: string; bg: string }> = {
  buy:  { color: "#10B981", bg: "rgba(16,185,129,0.12)" },
  hold: { color: "#F59E0B", bg: "rgba(245,158,11,0.12)" },
  sell: { color: "#F43F5E", bg: "rgba(244,63,94,0.12)"  },
};
const CAT_ICON: Record<string, string> = {
  gold: "🥇", equity: "📈", debt: "🏛️", real_estate: "🏠",
  crypto: "₿", fd: "🏦", mf: "📊", rd: "💰",
};

const DISCLAIMER = "⚠️ IMPORTANT DISCLAIMER: Investment plans are generated by AI for educational purposes only. FinanceAI does not promote, endorse, or have any affiliation with any organisation, fund, or platform mentioned. All investments carry risk including possible loss of principal. Past performance does not guarantee future results. Cryptocurrency and equity markets are highly volatile. Please consult a SEBI-registered (India) or SCA-licensed (UAE) financial advisor before investing. You invest entirely at your own risk.";

export default function InvestmentPlansPage() {
  // ALL hooks before early returns
  const { report, loading } = useReport();
  const [activeProfile, setActiveProfile] = useState<"conservative" | "moderate" | "aggressive">("moderate");
  const [expandedItem, setExpandedItem]   = useState<string | null>(null);

  const plans  = getInvestmentPlans(report);
  const cur    = plans.currency || report?.summary.currency || "AED";
  const active = plans.plans[activeProfile];

  if (loading) return <LoadingSpinner text="Generating investment plans…" />;

  const DisclaimerBanner = ({ size = "full" }: { size?: "full" | "compact" }) => (
    <div style={{
      padding: size === "full" ? "16px 20px" : "12px 16px",
      borderRadius: "14px", background: "rgba(245,158,11,0.07)",
      border: "2px solid rgba(245,158,11,0.25)",
      display: "flex", gap: "10px", alignItems: "flex-start",
    }}>
      <span style={{ fontSize: "18px", flexShrink: 0 }}>⚠️</span>
      <p style={{ fontSize: size === "full" ? "11px" : "10px", color: "#92400E", lineHeight: "1.6", fontWeight: "500" }}>
        {plans.disclaimer || DISCLAIMER}
      </p>
    </div>
  );

  // No plans yet — show placeholder
  if (!active || Object.keys(plans.plans).length === 0) return (
    <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
      <h1 style={{ fontSize: "22px", fontWeight: "800", color: "#0F172A" }}>Investment Plans</h1>
      <DisclaimerBanner />
      <div className="card-premium" style={{ padding: "48px", textAlign: "center" }}>
        <div style={{ fontSize: "48px", marginBottom: "12px" }}>💎</div>
        <h2 style={{ fontSize: "16px", fontWeight: "700", color: "#0F172A" }}>Plans not yet generated</h2>
        <p style={{ color: "#64748B", fontSize: "12px", marginTop: "6px", maxWidth: "300px", margin: "8px auto 0" }}>
          Upload a bank statement to generate personalised investment plans based on your actual surplus and health score.
        </p>
      </div>
    </div>
  );

  // Donut chart using SVG — simple arc per allocation
  function DonutChart({ allocs }: { allocs: typeof active.allocation }) {
    const r = 52, cx = 64, cy = 64;
    const circ = 2 * Math.PI * r;
    const colors = ["#10B981","#3B82F6","#F59E0B","#F43F5E","#8B5CF6","#14B8A6","#F97316","#EC4899"];
    let cumulative = 0;
    return (
      <svg width="128" height="128" viewBox="0 0 128 128">
        <circle cx={cx} cy={cy} r={r} fill="none" stroke="#F1F5F9" strokeWidth="20"/>
        {allocs.map((a, i) => {
          const pct    = a.percent / 100;
          const offset = circ - pct * circ;
          const rotate = (cumulative / 100) * 360 - 90;
          cumulative += a.percent;
          return (
            <circle key={i} cx={cx} cy={cy} r={r} fill="none"
              stroke={colors[i % colors.length]} strokeWidth="20"
              strokeDasharray={`${pct * circ} ${circ}`}
              strokeDashoffset={offset}
              transform={`rotate(${rotate} ${cx} ${cy})`}
            />
          );
        })}
        <text x={cx} y={cy - 4} textAnchor="middle" fontSize="11" fontWeight="800" fill="#0F172A">
          {active.expected_cagr ?? ""}
        </text>
        <text x={cx} y={cy + 10} textAnchor="middle" fontSize="8" fill="#94A3B8">CAGR</text>
      </svg>
    );
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
      {/* Header */}
      <div>
        <h1 style={{ fontSize: "22px", fontWeight: "800", color: "#0F172A" }}>Investment Plans</h1>
        <p style={{ color: "#94A3B8", fontSize: "13px", marginTop: "4px" }}>
          AI-generated plans based on your actual monthly surplus and risk appetite
          {plans.generated_for ? ` · ${plans.generated_for}` : ""}
        </p>
      </div>

      {/* Top disclaimer — NON-DISMISSABLE */}
      <DisclaimerBanner size="full" />

      {/* Risk profile selector */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "12px" }}>
        {(["conservative", "moderate", "aggressive"] as const).map(profile => {
          const meta = PROFILE_META[profile];
          const plan = plans.plans[profile];
          const isActive = activeProfile === profile;
          return (
            <button key={profile} onClick={() => setActiveProfile(profile)} style={{
              padding: "18px", borderRadius: "16px", cursor: "pointer", textAlign: "left",
              border: `2px solid ${isActive ? meta.color : "#E2E8F0"}`,
              background: isActive ? meta.bg : "white",
              transition: "all 0.2s",
            }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "10px" }}>
                <span style={{ fontSize: "24px" }}>{meta.icon}</span>
                {profile === "moderate" && (
                  <span style={{ fontSize: "9px", fontWeight: "700", padding: "2px 8px", borderRadius: "20px", background: "#3B82F6", color: "white" }}>POPULAR</span>
                )}
              </div>
              <p style={{ fontSize: "14px", fontWeight: "700", color: "#0F172A", textTransform: "capitalize", marginBottom: "3px" }}>{profile}</p>
              <p style={{ fontSize: "10px", color: "#94A3B8", marginBottom: "10px" }}>{meta.desc}</p>
              {plan && (
                <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
                  <span style={{ fontSize: "11px", fontWeight: "700", color: meta.color }}>
                    {formatCurrency(plan.monthly_investment, cur)}/mo
                  </span>
                  <span style={{ fontSize: "10px", color: "#94A3B8" }}>→ {formatCurrency(plan.target_5y, cur)} in 5y</span>
                </div>
              )}
            </button>
          );
        })}
      </div>

      {/* Active plan detail */}
      {active && (
        <>
          {/* Summary row */}
          <div style={{ display: "grid", gridTemplateColumns: "auto 1fr", gap: "20px", alignItems: "center" }}>
            <div className="card-premium" style={{ padding: "20px", display: "flex", flexDirection: "column", alignItems: "center" }}>
              <DonutChart allocs={active.allocation} />
              <p style={{ fontSize: "11px", color: "#94A3B8", marginTop: "8px", textAlign: "center" }}>Allocation mix</p>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
              <div className="card-premium" style={{ padding: "16px" }}>
                <p style={{ fontSize: "10px", color: "#94A3B8", marginBottom: "3px" }}>Monthly investment</p>
                <p style={{ fontSize: "22px", fontWeight: "800", color: PROFILE_META[activeProfile].color }}>
                  {formatCurrency(active.monthly_investment, cur)}
                </p>
              </div>
              <div className="card-premium" style={{ padding: "16px" }}>
                <p style={{ fontSize: "10px", color: "#94A3B8", marginBottom: "3px" }}>5-year target</p>
                <p style={{ fontSize: "22px", fontWeight: "800", color: "#0F172A" }}>
                  {formatCurrency(active.target_5y, cur)}
                </p>
              </div>
              {active.description && (
                <div style={{ padding: "14px", borderRadius: "12px", background: "#F8FAFC", border: "1px solid #F1F5F9" }}>
                  <p style={{ fontSize: "12px", color: "#374151", lineHeight: "1.55" }}>{active.description}</p>
                </div>
              )}
            </div>
          </div>

          {/* Allocation breakdown */}
          <div className="card-premium" style={{ padding: "20px" }}>
            <h2 style={{ fontSize: "14px", fontWeight: "600", color: "#0F172A", marginBottom: "14px" }}>
              Allocation breakdown — {activeProfile}
            </h2>
            <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
              {active.allocation.map((item, i) => {
                const isExp    = expandedItem === `${activeProfile}_${i}`;
                const sentStyle = SENTIMENT_STYLE[item.current_sentiment] ?? SENTIMENT_STYLE.hold;
                const colors    = ["#10B981","#3B82F6","#F59E0B","#F43F5E","#8B5CF6","#14B8A6","#F97316","#EC4899"];
                const barColor  = colors[i % colors.length];
                return (
                  <div key={i} style={{ borderRadius: "12px", border: "1px solid #F1F5F9", overflow: "hidden" }}>
                    <button onClick={() => setExpandedItem(isExp ? null : `${activeProfile}_${i}`)} style={{
                      width: "100%", padding: "12px 16px", background: isExp ? "#F8FAFC" : "white",
                      border: "none", cursor: "pointer", textAlign: "left",
                    }}>
                      <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                        <span style={{ fontSize: "18px" }}>{CAT_ICON[item.category] ?? "📦"}</span>
                        <div style={{ flex: 1 }}>
                          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "6px" }}>
                            <div style={{ display: "flex", alignItems: "center", gap: "8px", flexWrap: "wrap" }}>
                              <span style={{ fontSize: "13px", fontWeight: "600", color: "#0F172A" }}>{item.instrument}</span>
                              <span style={{ fontSize: "10px", fontWeight: "700", padding: "2px 8px", borderRadius: "20px", background: sentStyle.bg, color: sentStyle.color }}>
                                {item.current_sentiment.toUpperCase()}
                              </span>
                              <span style={{ fontSize: "10px", padding: "2px 7px", borderRadius: "20px", background: `${RISK_COLOR[item.risk] ?? "#64748B"}18`, color: RISK_COLOR[item.risk] ?? "#64748B" }}>
                                {item.risk} risk
                              </span>
                            </div>
                            <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                              <span style={{ fontSize: "13px", fontWeight: "800", color: barColor }}>{item.percent}%</span>
                              <span style={{ fontSize: "11px", color: "#10B981" }}>{item.expected_return}</span>
                              <span style={{ color: "#94A3B8", fontSize: "14px", transition: "transform 0.2s", transform: isExp ? "rotate(180deg)" : "none" }}>▾</span>
                            </div>
                          </div>
                          <div style={{ height: "6px", background: "#F1F5F9", borderRadius: "3px", overflow: "hidden" }}>
                            <div style={{ height: "6px", borderRadius: "3px", background: barColor, width: `${item.percent}%`, transition: "width 1s ease" }} />
                          </div>
                        </div>
                      </div>
                    </button>

                    {isExp && (
                      <div style={{ padding: "14px 16px", borderTop: "1px solid #F1F5F9", background: "#FAFAFA" }}>
                        <p style={{ fontSize: "12px", color: "#374151", marginBottom: "10px", lineHeight: "1.55" }}>
                          {item.rationale}
                        </p>
                        {item.platforms.length > 0 && (
                          <div style={{ marginBottom: "10px" }}>
                            <p style={{ fontSize: "10px", color: "#94A3B8", marginBottom: "5px", fontWeight: "600", textTransform: "uppercase" }}>
                              Example platforms
                            </p>
                            <div style={{ display: "flex", gap: "6px", flexWrap: "wrap" }}>
                              {item.platforms.map((p, pi) => (
                                <span key={pi} style={{ fontSize: "10px", padding: "3px 10px", borderRadius: "20px", background: "#F1F5F9", color: "#475569", border: "1px solid #E2E8F0" }}>
                                  {p}
                                </span>
                              ))}
                            </div>
                          </div>
                        )}
                        <p style={{ fontSize: "9px", color: "#CBD5E1", lineHeight: "1.4" }}>
                          ⚠️ Platform names are illustrative examples only. FinanceAI does not endorse or partner with any platform listed.
                        </p>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </>
      )}

      {/* Bottom disclaimer — NON-DISMISSABLE */}
      <DisclaimerBanner size="compact" />
    </div>
  );
}
