"""
Investment Plan Generator — 3 risk profiles with Groq.
Conservative / Moderate / Aggressive based on real surplus.
"""
from typing import List
from app.services.groq_service import GroqService

DISCLAIMER = ("⚠️ IMPORTANT DISCLAIMER: Investment plans are generated by AI for educational "
    "purposes only. FinanceAI does not promote or endorse any organisation, fund, or platform. "
    "All investments carry risk including loss of principal. Past performance does not guarantee "
    "future results. Consult a SEBI-registered (India) or SCA-licensed (UAE) advisor before "
    "investing. You invest entirely at your own risk.")

SYSTEM = """You are a financial planning AI. Generate 3 investment plans for this user.
Return ONLY valid JSON — no markdown, no explanation:
{
  "risk_profiles": ["conservative","moderate","aggressive"],
  "plans": {
    "conservative": {
      "label":"Conservative","description":"2 sentence summary",
      "monthly_investment":0,"target_5y":0,"expected_cagr":"8-10%",
      "allocation":[{"instrument":"string","category":"gold|equity|debt|real_estate|crypto|fd|mf|rd",
        "percent":0,"risk":"low|medium|high|very_high","expected_return":"string",
        "rationale":"string","platforms":["string"],"current_sentiment":"buy|hold|sell","disclaimer":true}]
    },
    "moderate":{"same shape"},"aggressive":{"same shape"}
  },
  "disclaimer":"string","currency":"AED","generated_for":"UAE"
}
Rules: base monthly_investment on actual surplus. Never endorse specific companies.
Add disclaimer:true to every allocation item. Include current_sentiment per 2024-2025 knowledge."""


class InvestmentPlannerAgent:
    def __init__(self, region: str = "UAE", currency: str = "AED"):
        self.groq = GroqService(); self.region = region; self.currency = currency

    def run(self, transactions: List[dict], health_score: dict, savings_forecast: dict = None) -> dict:
        from collections import defaultdict
        debits  = [t for t in transactions if t.get("type") == "debit"]
        credits = [t for t in transactions if t.get("type") == "credit"]
        income  = sum(t["amount"] for t in credits)
        spend   = sum(t["amount"] for t in debits)
        surplus = max(0, income - spend)
        hs      = (health_score or {}).get("overall_score", 50)
        cat     = defaultdict(float)
        for t in debits: cat[t.get("category","other")] += t["amount"]
        msg = (f"Region:{self.region} | Currency:{self.currency}\n"
               f"Income:{round(income,0)} Spend:{round(spend,0)} Surplus:{round(surplus,0)}\n"
               f"Health:{hs}/100 | Top cats:{dict(list(cat.items())[:4])}\n"
               f"Make monthly_investment realistic vs surplus {round(surplus,0)} {self.currency}.\n"
               f"Include current_sentiment per 2024-2025 trends. disclaimer:true on every allocation.")
        try:
            data = self.groq.extract_json(SYSTEM, msg, retries=3)
            data["disclaimer"] = DISCLAIMER; data["currency"] = self.currency
            for p in data.get("plans",{}).values():
                for item in p.get("allocation",[]): item["disclaimer"] = True
            return data
        except Exception as e:
            print(f"[InvestmentPlanner] Fallback: {e}")
            return self._fallback(surplus)

    def _fallback(self, surplus: float) -> dict:
        c, is_uae = self.currency, self.currency == "AED"
        def plan(label, pct, allocs, cagr):
            m = round(surplus * pct, 0)
            rate = float(cagr.split("-")[0]) / 100
            return {"label":label,"description":f"{label} plan allocating {int(pct*100)}% of surplus.",
                "monthly_investment":m,"target_5y":round(m*12*5*(1+rate),0),"expected_cagr":cagr,
                "allocation":allocs}
        if is_uae:
            cons = [{"instrument":"Gold ETF","category":"gold","percent":30,"risk":"low","expected_return":"8-10%","rationale":"Inflation hedge","platforms":["Sarwa","StashAway"],"current_sentiment":"buy","disclaimer":True},
                    {"instrument":"Fixed Deposit","category":"fd","percent":40,"risk":"low","expected_return":"4-5%","rationale":"Capital protected","platforms":["ADCB","FAB"],"current_sentiment":"hold","disclaimer":True},
                    {"instrument":"Govt Sukuk","category":"debt","percent":30,"risk":"low","expected_return":"4-5%","rationale":"Sharia-compliant bonds","platforms":["DIB","ADIB"],"current_sentiment":"hold","disclaimer":True}]
            mod  = [{"instrument":"Global ETF","category":"equity","percent":35,"risk":"medium","expected_return":"10-12%","rationale":"Broad market exposure","platforms":["Sarwa","StashAway"],"current_sentiment":"buy","disclaimer":True},
                    {"instrument":"Gold","category":"gold","percent":20,"risk":"low","expected_return":"8-10%","rationale":"Portfolio stabiliser","platforms":["DGCX"],"current_sentiment":"buy","disclaimer":True},
                    {"instrument":"Fixed Deposit","category":"fd","percent":25,"risk":"low","expected_return":"4-5%","rationale":"Stable base","platforms":["FAB"],"current_sentiment":"hold","disclaimer":True},
                    {"instrument":"REITs","category":"real_estate","percent":20,"risk":"medium","expected_return":"6-9%","rationale":"Property without buying","platforms":["Nasdaq Dubai"],"current_sentiment":"hold","disclaimer":True}]
            agg  = [{"instrument":"Global Equity ETF","category":"equity","percent":40,"risk":"high","expected_return":"12-15%","rationale":"Max equity exposure","platforms":["Interactive Brokers"],"current_sentiment":"buy","disclaimer":True},
                    {"instrument":"Crypto (BTC/ETH)","category":"crypto","percent":15,"risk":"very_high","expected_return":"variable","rationale":"High risk speculation","platforms":["Binance","Rain"],"current_sentiment":"hold","disclaimer":True},
                    {"instrument":"Stocks","category":"equity","percent":25,"risk":"high","expected_return":"15-20%","rationale":"Alpha generation","platforms":["DFM","NASDAQ Dubai"],"current_sentiment":"hold","disclaimer":True},
                    {"instrument":"REITs","category":"real_estate","percent":20,"risk":"medium","expected_return":"7-10%","rationale":"Diversification","platforms":["Nasdaq Dubai"],"current_sentiment":"hold","disclaimer":True}]
        else:
            cons = [{"instrument":"PPF","category":"fd","percent":40,"risk":"low","expected_return":"7.1%","rationale":"Govt-backed tax-free","platforms":["SBI","Post Office"],"current_sentiment":"hold","disclaimer":True},
                    {"instrument":"Gold ETF/SGB","category":"gold","percent":30,"risk":"low","expected_return":"8-10%","rationale":"Inflation hedge","platforms":["Groww","Zerodha"],"current_sentiment":"buy","disclaimer":True},
                    {"instrument":"Debt MF","category":"mf","percent":30,"risk":"low","expected_return":"6-8%","rationale":"Better than FD","platforms":["Groww"],"current_sentiment":"hold","disclaimer":True}]
            mod  = [{"instrument":"Nifty Index SIP","category":"mf","percent":40,"risk":"medium","expected_return":"12-15%","rationale":"Core wealth builder","platforms":["Groww","Zerodha"],"current_sentiment":"buy","disclaimer":True},
                    {"instrument":"Gold ETF","category":"gold","percent":20,"risk":"low","expected_return":"8-10%","rationale":"Inflation hedge","platforms":["Groww"],"current_sentiment":"buy","disclaimer":True},
                    {"instrument":"NPS","category":"rd","percent":20,"risk":"low","expected_return":"9-12%","rationale":"Tax benefit + retirement","platforms":["HDFC Pension"],"current_sentiment":"hold","disclaimer":True},
                    {"instrument":"Mid Cap SIP","category":"mf","percent":20,"risk":"high","expected_return":"15-18%","rationale":"Growth potential","platforms":["Kuvera"],"current_sentiment":"hold","disclaimer":True}]
            agg  = [{"instrument":"Small/Mid Cap SIP","category":"mf","percent":40,"risk":"high","expected_return":"18-22%","rationale":"Highest long-term returns","platforms":["Groww","Zerodha"],"current_sentiment":"buy","disclaimer":True},
                    {"instrument":"Crypto","category":"crypto","percent":10,"risk":"very_high","expected_return":"variable","rationale":"Speculative only","platforms":["CoinDCX"],"current_sentiment":"hold","disclaimer":True},
                    {"instrument":"Direct Stocks","category":"equity","percent":30,"risk":"high","expected_return":"15-25%","rationale":"Alpha via stock selection","platforms":["Zerodha"],"current_sentiment":"hold","disclaimer":True},
                    {"instrument":"REITs/InvITs","category":"real_estate","percent":20,"risk":"medium","expected_return":"8-12%","rationale":"Real asset liquidity","platforms":["BSE","NSE"],"current_sentiment":"hold","disclaimer":True}]
        return {"risk_profiles":["conservative","moderate","aggressive"],
            "plans":{"conservative":plan("Conservative",0.30,cons,"8-10"),
                     "moderate":plan("Moderate",0.50,mod,"11-13"),
                     "aggressive":plan("Aggressive",0.70,agg,"14-18")},
            "disclaimer":DISCLAIMER,"currency":c,"generated_for":self.region}
